### PR TITLE
cflib: create directories for make install

### PR DESCRIPTION
**Pull request by th-otto**

### CODE REVIEW

**Comment by mikrosk** [comment]
Needs cleanup, one functionality per PR (changes should be against freemint/lib:master).

**Comment by th-otto** [comment]
See comment in https://github.com/freemint/lib/pull/2#issuecomment-340953821

**Comment by mikrosk** [comment]
@th-otto I suggest to finish #2 (commit all except the % prefixes) then then cherry pick the last commit from here and done :)

**Comment by th-otto** [comment]
Last commit applied.

**Pull request closed without merging**
